#-[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp/"
bearer_token_env_var = "CODEX_GITHUB_PERSONAL_ACCESS_TOKEN"

[mcp_servers.chrome-devtools]
type = "stdio"
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest", "--browser-url=http://127.0.0.1:9222"]
startup_timeout_sec = 10

[mcp_servers.next-devtools]
type = "stdio"
command = "npx"
args = ["-y", "next-devtools-mcp@latest"]
startup_timeout_sec = 30
