# Overrides for the production environment.
logLevel: warn
storage:
  provider: r2
  bucket: sit-portal-onwalk-net
  region: auto
  endpoint: https://e71be5efb76a6c54f78f008da4404f00.r2.cloudflarestorage.com
  prefix: /
  publicBaseUrl: https://e71be5efb76a6c54f78f008da4404f00.r2.cloudflarestorage.com
  r2:
    endpoint: https://e71be5efb76a6c54f78f008da4404f00.r2.cloudflarestorage.com
    bucket: sit-portal-onwalk-net
    region: auto
    publicBaseUrl: https://e71be5efb76a6c54f78f008da4404f00.r2.cloudflarestorage.com
regions:
  cn:
    apiBaseUrl: https://cn-api.svc.plus
    authUrl: https://cn-accounts.svc.plus
    dashboardUrl: https://cn-console.svc.plus
  global:
    apiBaseUrl: https://global-api.svc.plus
    authUrl: https://global-accounts.svc.plus
    dashboardUrl: https://global-console.svc.plus
